spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/realmadred/cloudConfig
          username:
          password:
          search-paths: src/main/resources
eureka:
  instance:
    hostname: cloudconfig
  client:
    serviceUrl:
      defaultZone: http://192.168.127.1:8000/eureka/
server:
  port: 9000