spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/realmadred/cloudConfig
          search-paths:
server:
  port: 8081